name: Bug report
description: Fehler melden
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: "Was ist passiert?"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      description: "Was hättest du erwartet?"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Output
      description: "Fehlermeldungen, Stacktraces, relevante Ausschnitte"
      render: shell
    validations:
      required: false
