name: Feature request
description: Idee/Verbesserung vorschlagen
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: "Warum?"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Lösungsvorschlag
      description: "Wie könnte es aussehen?"
    validations:
      required: false
