name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 6 * * 1"   # montags 06:00 UTC wöchentlicher Gesundheitscheck

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff black pytest mypy pre-commit pip-audit

      - name: Pre-commit (enforce)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Type check (mypy)
        run: mypy .

      - name: Tests
        run: |
          if [ -d tests ]; then
            pytest -q --maxfail=1 --disable-warnings --junitxml=pytest.xml
          else
            echo "No tests/ folder – skipping tests." && echo "::notice::No tests"
          fi

      - name: Backtest report (if CSV present)
        run: |
          if [ -f bridge_out/reports/equity_curve.csv ]; then
            python scripts/backtest.py --csv bridge_out/reports/equity_curve.csv --out bridge_out/reports/equity_curve.png
          else
            echo "No equity_curve.csv – skipping backtest report."
          fi

      - name: Vulnerability scan (pip-audit)
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt -f cyclonedx -o sbom.json || true
          else
            pip-audit -f cyclonedx -o sbom.json || true
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts-${{ matrix.python-version }}
          path: |
            pytest.xml
            bridge_out/reports/equity_curve.png
            trading_log.csv
            sbom.json
          if-no-files-found: ignore
